FROM openjdk:8
RUN cd /var/lib/jenkins/workspace/FlashSale_Project/userManagement
ADD target/userManagement-0.0.1-SNAPSHOT.jar userManagement.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","userManagement.jar"]
